# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  host: srv-cas-mysql01.mysql.database.azure.com
  port: 3306
  encoding: utf8
  database: development
  pool: 5
  username: sysadmin@srv-cas-mysql01
  password: Ch4mp10n5!
test:
  adapter: mysql2
  host: srv-cas-mysql01.mysql.database.azure.com
  port: 3306
  encoding: utf8
  database: test
  pool: 5
  username: sysadmin@srv-cas-mysql01
  password: Ch4mp10n5!
production:
  adapter: mysql2
  host: srv-cas-mysql01.mysql.database.azure.com
  port: 3306
  encoding: utf8
  database: production
  pool: 5
  username: sysadmin@srv-cas-mysql01
  password: Ch4mp10n5!
